-- Shared input settings: Omarchy owns the defaults (including pointer speed,
-- keyboard repeat and touchpad scroll). Add intentional shared overrides here;
-- device-specific changes belong in hypr/hosts/<hostname>.lua.
