# Window rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# Hyprland 0.53+ syntax

# Ignore maximize requests from apps.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Ensure Cursor gets rounded corners (in case it doesn't respect global rounding)
windowrule = rounding 8, match:class ^(cursor|Cursor)$


